# Environment parameters
env_name: TurtleBot3_Circuit_Simple-v0
env_stage: l  # gazebo turtlebot3 stage number
seed: 1
random_seed: 2022
num_agents: 5
state_dim: 26
action_dim: 2
max_action: 1.5

# Training parameters
model: PDDRL
batch_size: 256
num_episodes: 2000
num_steps_train: 2000000  # number of episodes from all agents
max_ep_length: 500  # maximum number of steps per episode
replay_mem_size: 100000  # maximum capacity of replay memory
priority_alpha: 0.6  # 0.6 controls the randomness vs prioritisation of the prioritised sampling (0.0 = Uniform sampling, 1.0 = Greedy prioritisation)
priority_beta_start: 0.4  # 0.4 starting value of beta - controls to what degree IS weights influence the gradient updates to correct for the bias introduces by priority sampling (0 - no correction, 1 - full correction)
priority_beta_end: 1.0  # 1.0 beta will be linearly annelaed from its start value to this value thoughout training
priority_epsilon: 0.0001
discount_rate: 0.99  # Discount rate (gamma) for future rewards
n_step_return: 5  # number of future steps to collect experiences for N-step returns
update_agent_ep: 1  # agent gets latest parameters from learner every update_agent_ep episodes
replay_queue_size: 32  # 1024  # queue with replays from all the agents
batch_queue_size: 64  # queue with batches given to learner
save_reward_threshold: 5
replay_memory_prioritized: 0
num_episode_save: 50
device: cuda
action_prior: uniform
fixed_alpha: 0
alpha: 1.0
reward_scale: 1.0
clip_norm: 0.0
use_automatic_entropy_tuning: 1
num_quantiles: 51
obs_noise: 0

# LSTM parameters
sequence_size: 8
recurrent_policy: 1
num_lstm_cell: 1

# Network parameters
critic_learning_rate: 0.0005
actor_learning_rate: 0.0005
dense_size: 256  # size of the 2 hidden layers in networks
final_layer_init: 0.003
num_atoms: 51  # number of atoms in output layer of distributed critic
v_min: -20.0  # lower bound of critic value output distribution
v_max: 200.0  # upper bound of critic value output distribution
tau: 0.001  # parameter for soft target network updates

# Comet parameters
api_key: 53WlWYRLtr1QwZTbjazoEv35u
project_name: turtlebot3-recurrent
disabled: 0

# Miscellaneous
save_buffer: 0
results_path: results
test: 0
test_real: 0
test_trials: 4
